In [57]:
import numpy as np

In [58]:
def nonlin(x, deriv=False):  # Note: there is a typo on this line in the video
    if(deriv==True):
        return (x*(1-x))
    
    return 1/(1+np.exp(-x))  # this will map any value between 0 and 1, turns numbers into probabilties

In [59]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]]) # 4x3

In [60]:
X # input data, 4 training examples (rows) with three nerons (columns)

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [61]:
y = np.array([[0],
             [1],
             [1],
             [0]]) # output data, 4x1

In [62]:
y

array([[0],
       [1],
       [1],
       [0]])

In [63]:
np.random.seed(1)

In [64]:
# synapses, connections between each nerion in one layer to every neuron in the next layer
# note X has 3 cols 2 are inputs the 3rd is a bias term (cosntant term)
#syn0 below is are the weights from input layer to hidden layer, a 3x4 matrix becasue there are (2+1)=3 inputs and 4 nodes
#sun1 are the weights between the hidden layer and the output layer, 4x1 , 4 nodes in hidden layer produce the 
#inputs and one is for the output

In [65]:
#synapses, layers in our network mean we need 2 matricies; this is the nerual network
syn0 = 2*np.random.random((3,4)) - 1  # 3x4 matrix of weights ((2 inputs + 1 bias) x 4 nodes in the hidden layer)
syn1 = 2*np.random.random((4,1)) - 1  # 4x1 matrix of weights. (4 nodes x 1 output) - no bias term in the hidden layer
# starting with random weights is best practice for optimisation

In [66]:
syn0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [67]:
syn1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [68]:
# note each synapse has a random weight asssiged to it

In [69]:
# create our first layer

In [71]:
# training steo
for j in range(100000):
    l0 = X
    l1 = nonlin(np.dot(l0,syn0)) # note l0 is X which is 4x3, syn0 is 3x4 so output from np.dot is 4x4
    l2 = nonlin(np.dot(l1,syn1)) # then l1 is 4x4, syn1 4x1 so output from np.dot is 4x1
    
    l2_error = y - l2
    if(j % 10000) == 0:
        
        print("Error: " + str(np.mean(np.abs(l2_error))))
        
    l2_delta = l2_error*nonlin(l2, deriv=True) # 4x1 matrix l2 matrix updated probabilites
    
    l1_error = l2_delta.dot(syn1.T) # take the avove line result and dot product transpose of syn1, 4x1.1x4 = 4x4 = l1_error
    
    l1_delta = l1_error * nonlin(l1,deriv=True) # l1_delta is l1_error 4x4. probabilities l1 4x4 = 4x4.4x4 = 4x4
    
    #update weights (by the deltas) (no learning rate term)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
        
print('Output after training')
print(l2)

Error: 0.00318350238587
Error: 0.00293230634228
Error: 0.00273150641821
Error: 0.00256631724004
Error: 0.00242737608676
Error: 0.00230843116063
Error: 0.00220512937522
Error: 0.0021143350549
Error: 0.00203372513685
Error: 0.0019615374333
Output after training
[[ 0.00155944]
 [ 0.99806849]
 [ 0.99820156]
 [ 0.00229627]]
